name: Build CodePush Server Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/codepush-server.yml'

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - id: "meta"
      name: "Docker Meta"
      uses: "docker/metadata-action@v5.5.1"
      with:
        images: droppii.azurecr.io/droppii/codepush-server
        tags: |
          type=ref,event=branch
          type=sha

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: droppii.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.6.1
      with:
        driver: "docker-container"

    - name: Build and push CodePush Server Docker image
      uses: docker/build-push-action@v6.7.0
      with:
        context: api
        file: api/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max